import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { loadAllEntityUeis, loadEntity } from "@/lib/data";
import { detectorLabel } from "@/lib/detector-meta";
import {
  agencyShort,
  formatDate,
  formatDelta,
  formatInt,
  formatMoney,
  formatPercentile,
  formatScore,
} from "@/lib/format";
import { DetectorCard } from "@/components/DetectorCard";
import { DetectorDots } from "@/components/DetectorDots";
import { ScoreHistoryChart } from "@/components/ScoreHistoryChart";
import { FlaggedContractsTable } from "@/components/FlaggedContractsTable";

// Pre-render one page per top-N entity at build time.
export async function generateStaticParams() {
  return loadAllEntityUeis().map((uei) => ({ uei }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ uei: string }>;
}): Promise<Metadata> {
  const { uei } = await params;
  const entity = loadEntity(uei);
  if (!entity) return { title: "Not found — Fraudhound" };
  return {
    title: `${entity.name} — Fraudhound`,
    description: `Statistical scrutiny brief for ${entity.name} (UEI ${entity.uei}).`,
  };
}

export default async function EntityPage({
  params,
}: {
  params: Promise<{ uei: string }>;
}) {
  const { uei } = await params;
  const entity = loadEntity(uei);
  if (!entity) notFound();

  const delta = formatDelta(entity.composite_score_delta);
  const briefParagraphs = (entity.brief_text ?? "")
    .split("\n\n")
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      <Link
        href="/"
        className="text-sm font-medium text-mute hover:text-brick transition-colors"
      >
        ← Back to watchlist
      </Link>

      {/* Hero */}
      <header className="mt-6 border-b border-line pb-8">
        <h1 className="font-serif text-4xl font-bold leading-tight tracking-tight sm:text-5xl">
          {entity.name}
        </h1>
        <p className="mt-2 font-mono text-sm text-mute">
          UEI {entity.uei} ·{" "}
          {entity.naics_description ?? "Unknown industry"}
        </p>
        <p className="mt-1 text-sm text-mute">
          Primary agency: {entity.agency ?? "—"}
        </p>

        {/* Stat boxes */}
        <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <StatBox
            label="Composite"
            value={formatScore(entity.composite_score)}
            sub={
              delta.direction !== "none"
                ? `${delta.text} vs prior day`
                : "first scoring day"
            }
            subTone={
              delta.direction === "up"
                ? "up"
                : delta.direction === "down"
                ? "down"
                : "neutral"
            }
          />
          <StatBox
            label="Percentile"
            value={formatPercentile(entity.composite_percentile_rank)}
            sub="among flagged today"
          />
          <StatBox
            label="Lifetime $"
            value={formatMoney(entity.lifetime_total)}
            sub="across all federal awards"
          />
          <StatBox
            label="Awards"
            value={formatInt(entity.lifetime_awards)}
            sub="lifetime count"
          />
        </div>

        {/* Detector strip */}
        <div className="mt-6 flex flex-wrap items-center gap-3 text-xs uppercase tracking-wide text-mute">
          <span>Detectors fired today:</span>
          <DetectorDots count={entity.detectors.length} />
          <span className="flex flex-wrap gap-x-3 text-charcoal">
            {entity.detectors.map((d) => (
              <span key={d.name} className="font-medium">
                ● {detectorLabel(d.name)}
              </span>
            ))}
          </span>
        </div>

        <p className="mt-6 text-xs text-mute">
          Scored {formatDate(entity.score_date)} · {agencyShort(entity.agency)}
        </p>
      </header>

      {/* The brief */}
      <section className="py-10 border-b border-line">
        <h2 className="text-xs font-medium uppercase tracking-[0.18em] text-mute">
          The brief
        </h2>
        <div className="mt-4 space-y-5">
          {briefParagraphs.length > 0 ? (
            briefParagraphs.map((p, i) => (
              <p
                key={i}
                className="font-serif text-base leading-relaxed text-charcoal"
              >
                {p}
              </p>
            ))
          ) : (
            <p className="font-serif italic text-mute">
              Brief not yet generated for this entity.
            </p>
          )}
        </div>
        <p className="mt-6 text-xs text-mute">
          Auto-generated by AI ·{" "}
          <Link href="/about" className="text-brick hover:underline">
            Methodology →
          </Link>
        </p>
      </section>

      {/* Detector breakdown */}
      <section className="py-10 border-b border-line">
        <h2 className="text-xs font-medium uppercase tracking-[0.18em] text-mute">
          Detector breakdown
        </h2>
        <div className="mt-4 grid gap-4">
          {entity.detectors.map((d) => (
            <DetectorCard key={d.name} finding={d} />
          ))}
        </div>
      </section>

      {/* Score history */}
      <section className="py-10 border-b border-line">
        <h2 className="text-xs font-medium uppercase tracking-[0.18em] text-mute">
          Score over time
        </h2>
        <div className="mt-4">
          <ScoreHistoryChart history={entity.score_history} />
        </div>
      </section>

      {/* Flagged contracts */}
      <section className="py-10">
        <h2 className="text-xs font-medium uppercase tracking-[0.18em] text-mute">
          Flagged contracts
        </h2>
        <p className="mt-2 text-sm text-mute">
          Contracts that triggered one or more detectors above.
        </p>
        <div className="mt-4">
          <FlaggedContractsTable contracts={entity.flagged_contracts} />
        </div>
        <p className="mt-4 text-sm">
          <a
            href={`https://www.usaspending.gov/search/?hash=&keyword=${entity.name}`}
            target="_blank"
            rel="noreferrer"
            className="text-brick hover:underline"
          >
            View all contracts for {entity.name} on USAspending.gov →
          </a>
        </p>
      </section>
    </div>
  );
}

function StatBox({
  label,
  value,
  sub,
  subTone = "neutral",
}: {
  label: string;
  value: string;
  sub: string;
  subTone?: "up" | "down" | "neutral";
}) {
  const subColor =
    subTone === "up"
      ? "text-brick"
      : subTone === "down"
      ? "text-mute"
      : "text-mute";
  return (
    <div className="rounded-lg border border-line bg-paper p-4">
      <p className="text-[10px] font-medium uppercase tracking-wide text-mute">
        {label}
      </p>
      <p className="mt-1 font-mono text-2xl font-medium text-charcoal">
        {value}
      </p>
      <p className={`mt-1 text-xs ${subColor}`}>{sub}</p>
    </div>
  );
}
